### ISSUE TITLE
Maya Collect Render Layers

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#3021]
**Describe the bug**
Publishing a render instance in Maya is broken

**To Reproduce**
1. Open Maya scene in lighting/lookdev context
2. Make sure scene is set to any render engine other than Maya software
3. Create a render instance
4. Run Publish

```
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\collect_render.py", line 192, in process
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 164, in get
    return renderer(layer, render_instance)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 187, in __init__
    self.layer_data.products = self.get_render_products()
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 1072, in get_render_products
    enabled = self._get_attr(aov, "enabled")
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_renderproducts.py", line 294, in _get_attr
    return lib.get_attr_in_layer(plug, layer=self.layer)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib.py", line 2550, in get_attr_in_layer
    return lib_rendersetup.get_attr_in_layer(attr, layer)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_rendersetup.py", line 150, in get_attr_in_layer
    overrides = get_attr_overrides(node_attr, layer)
  File "D:\REPO\OpenPype\openpype\hosts\maya\api\lib_rendersetup.py", line 264, in get_attr_overrides
    sel.add(node_attr)
RuntimeError: (kInvalidParameter): Object does not exist
```

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/161964224-63bec74a-03fb-4cbd-893d-1d40d506c622.png)

probably related to #3020 

[cuID:OP-3040]

**Comment by BigRoy** [comment]
Can you confirm whether you have Render Setup enabled or disabled?

**Comment by m-u-r-p-h-y** [comment]
Tested with Arnold, Redshift, Renderman

only RenderMan is having the issue. So it seems like it is connected to #3006 ?
