### ISSUE TITLE
Publishing of Tile render is not working with Draft

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#3764]
**Describe the bug**

When tile render is submitted to Deadline farm with Draft plugin set in settings:

the tiles are rendered correctly

![image](https://user-images.githubusercontent.com/352795/187657488-90d5a8a8-b1e6-457c-a5f4-031d5cd289bb.png)

the tiles are assembled correctly

![image](https://user-images.githubusercontent.com/352795/187657417-1d247787-f942-4f43-b93d-60782e214b71.png)

but it fails on publish as there is a mismatch of the file name (frame number?)

```
2022-08-31 12:22:15:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2022-08-31 12:22:15:  0: STDOUT:   File "d:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2022-08-31 12:22:15:  0: STDOUT:     runner(*args)
2022-08-31 12:22:15:  0: STDOUT:   File "d:\REPO\OpenPype\openpype\modules\deadline\plugins\publish\validate_expected_and_rendered_files.py", line 72, in process
2022-08-31 12:22:15:  0: STDOUT: RuntimeError: Missing expected files: ['Main_beauty.0001.exr']
2022-08-31 12:22:15:  0: STDOUT: Traceback (most recent call last):
2022-08-31 12:22:15:  0: STDOUT:   File "d:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2022-08-31 12:22:15:  0: STDOUT:     runner(*args)
2022-08-31 12:22:15:  0: STDOUT:   File "<string>", line 72, in process
2022-08-31 12:22:15:  0: STDOUT: RuntimeError: Missing expected files: ['Main_beauty.0001.exr']
2022-08-31 12:22:15:  0: STDOUT: !!! ERR: 2022-08-31 12:22:15,464 >>> { CLI-publish }: [  FAILED ValidateExpectedFiles: Missing expected files: ['Main_beauty.0001.exr'] -- ('d:\\REPO\\OpenPype\\openpype\\modules\\deadline\\plugins\\publish\\validate_expected_and_rendered_files.py', 72, 'process', '')  ] 
2022-08-31 12:22:15:  0: STDOUT: >>> run disk mapping command ...
```

Draft is producing 

`final output location: D:/PROJECTS/murphy_22101/shots/sh030/work/lighting/renders/maya/22101_sh030_workfileLighting_v011/Main/Main_beauty.1001.exr`

But publish is looking for `Main_beauty.0001.exr`

[cuID:OP-3860]

**Comment by vonbehr** [comment]
It works as long as you render frame 1.

**Comment by BigRoy** [comment]
@vonbehr what were the filenames you ended up with for that single frame? Did those differ from what @m-u-r-p-h-y described?

**Comment by m-u-r-p-h-y** [comment]
it works if your render sequence starts with frame `0001` 

that is the issue.
default OP sequence usually starts with `1001` and publish should know that . . .

**Comment by BigRoy** [comment]
Ah sorry - I read the other comments as "as long as you write 1 frame" instead of "as long as you write frame 1". Thanks for clarifying.

**Comment by tokejepsen** [comment]
Fixed in https://github.com/ynput/OpenPype/releases/tag/3.15.4
