### ISSUE TITLE
Ftrack: Sync sets assets data as None

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3797]
**Describe the bug**

I created a new Mongo database, created a new Project in Ftrack, synced a project from Ftrack, launched Maya then tried to publish a model. It failed.

It fails on Validate Maya Units with **Scene must be None FPS (now is 25.0)**.

Repair errors on:
```python
Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\action.py", line 90, in process
    plugin.repair(context)
  File "S:\openpype\OpenPype\openpype\hosts\maya\plugins\publish\validate_maya_units.py", line 99, in repair
  File "S:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 2087, in set_scene_fps
    dec, ipart = math.modf(fps)
TypeError: must be real number, not NoneType
```

It seems the Asset has synced with the following data as None.
**The syncing reported no errors.**

![afbeelding](https://user-images.githubusercontent.com/2439881/188644158-2e9afcac-4762-4a77-8a61-a0b239c50569.png)

---

Likely the issue is related to not having pressed "Ftrack > Actions > Prepare Project" because doing:

1. Prepare Project
2. Sync to OpenPype
3. Now data is synced.

**To Reproduce**

1. Create a new project in Ftrack
4. Add an asset + task
5. Right click on the project, Admin Actions -> Sync to OpenPype

**Expected behavior**

Syncing should error and tell me how to solve it - e.g. highlight that I should be doing `Prepare Project` instead of syncing  broken assets.

[cuID:[OP-3912](https://app.clickup.com/t/2u0j1be)]

**Comment by BigRoy** [comment]
Not relevant for AYON afaik.
