### ISSUE TITLE
Error when repairing render settings

### ISSUE THREAD

**Issue by vonbehr** [ynput/OpenPype#3899]
**Running version**
3.12.2

**Describe the bug**
Using _repair_ on a _Render Settings_ validation error results in this error message:

```
// Error: pyblish.plugin : Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Users\florianbehr\AppData\Local\pypeclub\openpype\openpype-v3.12.2\openpype\action.py", line 65, in process
    plugin.repair(instance)
  File "C:\Users\florianbehr\AppData\Local\pypeclub\openpype\openpype-v3.12.2\openpype\hosts\maya\plugins\publish\validate_rendersettings.py", line 324, in repair
RuntimeError: Item not found: _

Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Users\florianbehr\AppData\Local\pypeclub\openpype\openpype-v3.12.2\openpype\action.py", line 65, in process
    plugin.repair(instance)
  File "<string>", line 324, in repair
RuntimeError: Item not found: _
 // 
```

**To Reproduce**
1. Configure some attributes to validate in `project_settings/maya/publish/ValidateRenderSettings/vray_render_attributes`
2. Create a scene in Maya
3. Change some render settings so they will cause the validator to error
4. Create a render family
5. Run publish
6. Try repair on the render settings error

**Expected behavior**
The attributes with wrong values should be set to the expected values.

**Desktop (please complete the following information):**
 - OS: Windows
 - Host: Maya

[cuID:[OP-4141](https://app.clickup.com/t/2w5bzfe)]

**Comment by BigRoy** [comment]
This issue is actually not related to the `vray_render_attributes` but is logic related to the AOV / RenderElement separator.

It fails on [this line](https://github.com/pypeclub/OpenPype/blob/3.12.2/openpype/hosts/maya/plugins/publish/validate_rendersettings.py#L323-L324) which is still broken in [develop](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/validate_rendersettings.py#L334-L335) where it should be doing it like [how it's done in the RenderSettings](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/api/lib_rendersettings.py#L176-L190).

**Comment by vonbehr** [comment]
I still get the same error message even if I open the render settings before running validation.
