### ISSUE TITLE
OpenPype process and headless mode version not found error

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#3999]
## Problem

If version is specified and headless mode is enabled, OpenPype will just silently crash. Without headless mode window will popup saying that requested version was not found. This is confusing when trying to debug what's happening for example on Deadline.

[cuID:2zcab6e]

**Comment by antirotor** [comment]
now it crashes with traceback, so it can be cought:

```
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\start.py", line 1191, in <module>
    boot()
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\start.py", line 1066, in boot
    version_path = _bootstrap_from_code(use_version)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\start.py", line 835, in _bootstrap_from_code
    raise OpenPypeVersionIncompatible(
igniter.tools.OpenPypeVersionIncompatible: Requested version "3.14.15-nightly.2" was not found.
```
