### ISSUE TITLE
Maya: Template builder issue

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#4287]
**Running version**
3.14.10-nightly.6 (code)

**Describe the bug**
There is an issue with building a scene using Template builder.

**To Reproduce**
1. Setup simple template
![image](https://user-images.githubusercontent.com/352795/211031486-78c5d6ea-c3e0-4c03-850f-224bfbf510e1.png)

2. Set the correct path to the template in the settings under `project_settings/maya/templated_workfile_build`
![image](https://user-images.githubusercontent.com/352795/211031618-44eb261f-bbdc-4967-a9b7-d58b11d605b7.png)

5. Build the file from the template (under correct context from the settings)
![image](https://user-images.githubusercontent.com/352795/211031878-876cb3de-b1b7-4400-bd3b-da363453b5c1.png)

7. See error

```
# # *** WRN: >>> { <openpype.hosts.maya.api.workfile_template_builder.MayaTemplateBuilder object at 0x00000222E9AFE9B0> }: [ Failed to process placeholder |All_assets_grp|All_model_assets with plugin MayaPlaceholderLoadPlugin ] 
# ==============================
# No object matches name: |All_assets_grp|All_model_assets
# ==============================
# Traceback (most recent call last):
#   File "D:\REPO\OpenPype\openpype\pipeline\workfile\workfile_template_builder.py", line 585, in populate_scene_placeholders
#     placeholder_plugin.populate_placeholder(placeholder)
#   File "D:\REPO\OpenPype\openpype\hosts\maya\api\workfile_template_builder.py", line 208, in populate_placeholder
#     self.populate_load_placeholder(placeholder)
#   File "D:\REPO\OpenPype\openpype\pipeline\workfile\workfile_template_builder.py", line 1462, in populate_load_placeholder
#     self.load_succeed(placeholder, container)
#   File "D:\REPO\OpenPype\openpype\hosts\maya\api\workfile_template_builder.py", line 243, in load_succeed
#     self._parent_in_hierarchy(placeholder, container)
#   File "D:\REPO\OpenPype\openpype\hosts\maya\api\workfile_template_builder.py", line 277, in _parent_in_hierarchy
#     worldSpace=True
ValueError: No object matches name: |All_assets_grp|All_model_assets
```

**Comment by LiborBatek** [comment]
I think its wrong set of the placeholder. You didnt specified which asset should be used/loaded I guess...

**Comment by m-u-r-p-h-y** [comment]
it clearly says to load all assets of abc family using reference loader. Not sure what "set" you mean?
And it will load them actually
<img width="216" alt="image" src="https://user-images.githubusercontent.com/352795/211079010-b9d4803d-ff9b-405c-bf11-40452cb6b16d.png">
