### ISSUE TITLE
Global: colorspace config failing on unsupported file types

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4389]
I cannot publish e.g. a `pointcache` instance:

```python
Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\plugins\publish\extract_colorspace_data.py", line 46, in process
  File "S:\openpype\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 376, in set_representation_colorspace
    colorspace_settings = self.get_colorspace_settings(context)
  File "S:\openpype\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 331, in get_colorspace_settings
    anatomy_data=anatomy_data
  File "S:\openpype\OpenPype\openpype\pipeline\colorspace.py", line 365, in get_imageio_config
    "No OCIO config found in settings. It is "
FileExistsError: No OCIO config found in settings. It is either missing or there is typo in path inputs
```

This also goes to show this Extractor is INVALID.

Because additonally: **it shouldn't enforce injecting colorspaceData for representations which are NOT a image/video/pixel format like e.g. a pointcache.**
Plus it shouldn't fail if nog config is set.

Also `FileExistsError` sounds like it's exactly the opposite of what is actually occurring here, no?

_Originally posted by @BigRoy in https://github.com/ynput/OpenPype/pull/4195#discussion_r1088476284_

**Comment by jakubjezek001** [comment]
fixed by https://github.com/ynput/OpenPype/pull/4390
