### ISSUE TITLE
Nuke: conversion of old publishing instances crashes

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4476]
**Running version**
3.15.1-nightly.6

**Describe the bug**
Conversion of old publishing instances to new doesn't work.

<details>
<summary>See traceback:</summary>

```python
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\pipeline\create\context.py", line 2371, in run_convertors
    self.run_convertor(convertor_identifier)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\pipeline\create\context.py", line 2352, in run_convertor
    convertor.convert()
  File "<string>", line 47, in convert
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\hosts\nuke\api\plugin.py", line 1151, in convert_to_valid_instaces
    if "_publisherConvert" not in current_file:
TypeError: argument of type 'NoneType' is not iterable
```
</details>

**To Reproduce**
1. In Nuke, open scene with old instances.
2. Open Publisher
3. Hit **Update subsets** on **Convert legacy**
4. See the error

**Expected behavior**
Old instances should be converted to new one as expected.

**Screenshots**
Broken instance:
![image](https://user-images.githubusercontent.com/33513211/219355188-365817c2-6319-4cb9-a0bc-cce0dfd87ba1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Nuke 11.3v6

[cuID:[OP-4969](https://app.clickup.com/t/863g2zrac)]

**Comment by jakubjezek001** [comment]
I am on `3.15.2-nightly.1` in Windows os  testing it at Nuke 11.3v6 and all works fine.
