### ISSUE TITLE
3dsmax: Unable to delete loaded asset in the Scene Inventory

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#4505]
Running OP 3.15.2 (from source) Im not able to delete asset via ```Scene Inventory```.

Getting this error msg
```
Traceback (most recent call last):
  File "D:\REPO\OP_3\openpype\tools\sceneinventory\view.py", line 299, in <lambda>
    lambda: self._show_remove_warning_dialog(items))
  File "D:\REPO\OP_3\openpype\tools\sceneinventory\view.py", line 774, in _show_remove_warning_dialog
    remove_container(item)
  File "D:\REPO\OP_3\openpype\pipeline\load\utils.py", line 438, in remove_container
    return loader.remove(container)
  File "D:\REPO\OP_3\openpype\hosts\max\plugins\load\load_pointcache.py", line 83, in remove
    node = container["node"]
KeyError: 'node'
```

**Comment by BigRoy** [comment]
I suppose this issue was resolved with this PR: https://github.com/ynput/OpenPype/pull/4507

Correct @LiborBatek @moonyuet ?

**Comment by LiborBatek** [comment]
@BigRoy I think so! I have tested it and was all ok in that #4507 

...so I guess this PR being just dulpicate and not just closed?

**Comment by BigRoy** [comment]
> ...so I guess this PR being just dulpicate and not just closed?

This isn't a PR but an issue. An I suspect this issue was just related to that PR - so I'm closing this.
