### ISSUE TITLE
Publisher: Attribute defs without key

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4533]
**Running version**
3.15.2-nightly.1

**Describe the bug**
if `UISeparatorDef()` added to **get_attribute_defs** on any  plugin with **OpenPypePyblishPluginMixin** class.
```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\tools\publisher\widgets\overview_widget.py", line 268, in _on_subset_change
    instances, context_selected, convertor_identifiers
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\tools\publisher\widgets\widgets.py", line 1674, in set_current_instances
    instances, context_selected
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\tools\publisher\widgets\widgets.py", line 1441, in set_current_instances
    instances, context_selected
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\tools\publisher\control.py", line 1945, in get_publish_attribute_definitions
    value = attr_val[attr_def.key]
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\create\context.py", line 572, in __getitem__
    return self._data[key]
KeyError: None
```

[cuID:[OP-5021](https://app.clickup.com/t/861me03k5)]

**Comment by iLLiCiTiT** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/4534
