### ISSUE TITLE
Global: workfile template builder Creators failing

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4542]
**Running version**
3.15.2-nightly.2

**Describe the bug**
Creator placeholders are not resolving. Following was returned from Nuke template.

```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\pipeline.py", line 294, in <lambda>
    lambda: build_workfile_template()
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\workfile_template_builder.py", line 971, in build_workfile_template
    builder.build_template()
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\workfile\workfile_template_builder.py", line 454, in build_template
    level_limit, keep_placeholders)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\workfile\workfile_template_builder.py", line 559, in populate_scene_placeholders
    placeholders = self.get_placeholders()
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\workfile\workfile_template_builder.py", line 406, in get_placeholders
    result = placeholder_plugin.collect_placeholders()
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\workfile_template_builder.py", line 609, in collect_placeholders
    placeholder_data = self._parse_placeholder_node_data(node)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\workfile_template_builder.py", line 576, in _parse_placeholder_node_data
    )._parse_placeholder_node_data(node)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\workfile_template_builder.py", line 130, in _parse_placeholder_node_data
    for key in self.get_placeholder_keys():
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\workfile\workfile_template_builder.py", line 877, in get_placeholder_keys
    option_keys = get_attributes_keys(self.get_placeholder_options())
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\hosts\nuke\api\workfile_template_builder.py", line 624, in get_placeholder_options
    return self.get_create_plugin_options(options)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\pipeline\workfile\workfile_template_builder.py", line 1560, in get_create_plugin_options
    "Creator"
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\lib\attribute_definitions.py", line 85, in __call__
    obj = super(AbstractAttrDefMeta, self).__call__(*args, **kwargs)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\lib\attribute_definitions.py", line 442, in __init__
    ).format(self.__class__.__name__))
ValueError: Empty 'items' value. EnumDef must have defined values on initialization.
```

**To Reproduce**
1. Go to Studio Project Setting and paste following content of zip to `project_settings/nuke/templated_workfile_build/profiles`
[workfile_template_builder_test_files.zip](https://github.com/ynput/OpenPype/files/10849472/workfile_template_builder_test_files.zip)
2. open Nuke at the testing project and use template builder
![image](https://user-images.githubusercontent.com/40640033/221836050-d5491736-e58d-4f4b-8d88-ac74b753a6d3.png)

**Expected behavior**
At least render Write at the end of template node graph should be resolved

[cuID:[OP-5037](https://app.clickup.com/t/863g5ew03)]

**Comment by jakubjezek001** [comment]
fix was implemented with https://github.com/ynput/OpenPype/pull/4545
