### ISSUE TITLE
global: `collect_anatomy_instance_data` json serialization issue

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4568]
**Running version**
3.15.2-nightly.3

**Describe the bug**
```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype_3.15_up\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\plugins\publish\collect_anatomy_instance_data.py", line 55, in process
    self.fill_anatomy_data(context)
  File "C:\CODE\__PYPE\OpenPype_3.15_up\openpype\plugins\publish\collect_anatomy_instance_data.py", line 295, in fill_anatomy_data
    json.dumps(anatomy_data, indent=4)
  File "C:\Program Files\Nuke13.2v5\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Program Files\Nuke13.2v5\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RootItem is not JSON serializable
```

**To Reproduce**
1. Open nuke at testing scene
2. Publisher and hit validate
3. then reload publisher
4. Hit Validate again

**Expected behavior**
Should publish as usual

[cuID:[OP-5181](https://app.clickup.com/t/861meqgqa)]

**Comment by jakubjezek001** [comment]
Related to an issue in https://github.com/ynput/OpenPype/pull/4556. Anatomy data were not deepcopy-ied
