### ISSUE TITLE
Scene Inventory: Cherry Picking hierarchy error for new style hosts

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4593]
**Running version**
3.15.2-nightly.4

**Describe the bug**

[This particular line of code](https://github.com/ynput/OpenPype/blob/develop/openpype/tools/sceneinventory/model.py#L211) for the Scene Inventory / Manager will fail for most hosts and especially new style hosts since `host.pipeline` isn't a thing on it. 🙂

You'll hit this error if you "Cherry Pick" in the loader. (I've personally never used that, but maybe others do?) 

The only host having a [`update_hierarchy` function implemented is Blender](https://github.com/ynput/OpenPype/blob/79e6de15b56ac9c3b2c60a1278b09958df1d67e3/openpype/hosts/blender/api/pipeline.py#L379-L406
). It's the only update_hierarchy function in the codebase 🙂

- Is cherry-picking still ever a thing?
- Are hierarchies like that in the scene inventory a thing? And where is it used in OP?

Doesn't seem like it's getting much use? It originates from Avalon, see the [Avalon Hierarchy View PR](https://github.com/getavalon/core/pull/353).

**To Reproduce**

1. Go to a new style host, e.g. houdini, nuke, after effects
2. Go to Scene Inventory
3. Right click on the child item, a specific container, and then click Cherry Pick.
4. Refreshing will then report an error

Example error:
```python
Traceback (most recent call last):
  File "S:\openpype\OpenPype\openpype\tools\sceneinventory\window.py", line 156, in refresh
    self._model.refresh(**kwargs)
  File "S:\openpype\OpenPype\openpype\tools\sceneinventory\model.py", line 211, in refresh
    if not hasattr(host.pipeline, "update_hierarchy"):
AttributeError: 'FusionHost' object has no attribute 'pipeline'
```

**Expected behavior**

No errors.

**Additional context**

Hierarchy views and cherry picking originate from Avalon, see [this Avalon Hierarchy View PR](https://github.com/getavalon/core/pull/353)

**Comment by LiborBatek** [comment]
@iLLiCiTiT Can be closed then?
