### ISSUE TITLE
SFTP site raises an error in local settings project

### ISSUE THREAD

**Issue by Tilix4** [ynput/OpenPype#4705]
**Running version**
3.15.1

**Describe the bug**
Adding a sftp site raises an error and breaks the local settings UI.

```
Traceback (most recent call last):
  File "/Users/felixdavid/Documents/Logiciels/OpenPype/openpype/tools/settings/local_settings/projects_widget.py", line 851, in _on_project_change
    self.roos_site_widget.change_project(project_name)
  File "/Users/felixdavid/Documents/Logiciels/OpenPype/openpype/tools/settings/local_settings/projects_widget.py", line 811, in change_project
    self.sites_widget.change_project(project_name)
  File "/Users/felixdavid/Documents/Logiciels/OpenPype/openpype/tools/settings/local_settings/projects_widget.py", line 443, in change_project
    self.refresh()
  File "/Users/felixdavid/Documents/Logiciels/OpenPype/openpype/tools/settings/local_settings/projects_widget.py", line 359, in refresh
    for site_name, site_inputs in self._get_sites_inputs():
  File "/Users/felixdavid/Documents/Logiciels/OpenPype/openpype/tools/settings/local_settings/projects_widget.py", line 294, in _get_sites_inputs
    platform_value = path_entity[platform.system().lower()]
TypeError: string indices must be integers
```

**To Reproduce**
1. Create SFTP site
2. In local settings, pick a project (other than `Default`
3. Set `remote` to your sftp site
4. The error is raised and you cannot override roots

**Expected behavior**
Usual behaviour with ability to set roots.

**Screenshots**
<img width="708" alt="Capture d’écran 2023-03-24 à 13 40 46" src="https://user-images.githubusercontent.com/22875539/227523909-211d2bbc-2cbf-4430-b095-895386d7544a.png">

**Desktop (please complete the following information):**
 - OS: All

**Comment by kalisp** [comment]
Should be fixed by https://github.com/ynput/OpenPype/pull/4563

**Comment by Tilix4** [comment]
Indeed, fixed by https://github.com/ynput/OpenPype/pull/4563
