### ISSUE TITLE
Maya: Set Context fails for new scene for V-Ray renderer

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4706]
**Running version**

3.15.2

**Describe the bug**

When trying to set the resolution in Maya using V-Ray renderer but there's no VRaySettings node (yet?) then an error will occur in the code. This will for example happen on "new scene" when using V-Ray as renderer.

```
file -f -new;
# openpype.hosts.maya : Running callback on new..
# openpype.hosts.maya.api.lib : Setting scene FPS to: 'film'
# Error: openpype.hosts.maya.api.lib : Can't set VRay resolution because there is no node named: `vraySettings` # 
# openpype.hosts.maya.api.lib : Setting scene resolution to: 1920 x 1080
# Warning: EventCallback : Failed to execute event callback < EventCallback - on_new > C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\hosts\maya\api\pipeline.py
Traceback (most recent call last):
  File "C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\lib\events.py", line 195, in process_event
    callback()
  File "C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\hosts\maya\api\pipeline.py", line 630, in on_new
    lib.set_context_settings()
  File "C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\hosts\maya\api\lib.py", line 2184, in set_context_settings
    reset_scene_resolution()
  File "C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\hosts\maya\api\lib.py", line 2152, in reset_scene_resolution
    set_scene_resolution(width, height, pixelAspect)
  File "C:\Users\Dillon\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.2\openpype\hosts\maya\api\lib.py", line 2062, in set_scene_resolution
    "{}.{}".format(control_node, aspect_ratio_attr), deviceAspectRatio)
RuntimeError: setAttr: No object matches name: defaultResolution.aspectRatio
```

It's because [it continues here](https://github.com/ynput/OpenPype/blob/a74e62a482ae0e8a1ef081cc3a85d3aa1a173258/openpype/hosts/maya/api/lib.py#L2052-L2054) but then using the wrong attribute name (that's only valid for the v-ray node).

> It's because `VRaySettings` node does not exist yet, but it still continues trying to set the resolution but then with the wrong attribute on the `defaultResolution`.
> Because it had already overridden the `aspect_ratio_attr` for V-Ray but that's not the valid attribute for the default resolution node.

We should likely best case scenario force the VRaySettings node creation so that if V-Ray is the renderer but it did not exist yet that we'd create it.

[Issue originally reported by Dillon Sinden (Lucan) on Discord](https://discord.com/channels/517362899170230292/1088411966135083030/1088807144020787312)

**To Reproduce**

1. Use V-Ray as renderer 
    - (It might be that you need to set it as the "preferred renderer" in preferences so that the new scene initializes with it directly.)
2. Create new file

**Expected behavior**

No error, resolution should still be correct for V-Ray renderer.

[cuID:[OP-5367](https://app.clickup.com/t/861mjda5b)]

**Comment by BigRoy** [comment]
No idea if still relevant in AYON - but I'll close it and see if it comes up for ayon-maya over time.
