### ISSUE TITLE
Bug: Ayon - integrating hero version fails (within maya)

### ISSUE THREAD

**Issue by sjt-rvx** [ynput/OpenPype#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Standard model publish, integrating a hero version fails with this error message:

```
Instance: 
modelMain
Message: 
Object of type object is not JSON serializable
Line: 
179
Traceback: 
Traceback (most recent call last):
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/pyblish/plugin.py", line 522, in __explicit_process
    runner(*args)
  File "/cache/dev/OpenPype/openpype/plugins/publish/integrate_hero_version.py", line 98, in process
  File "/cache/dev/OpenPype/openpype/plugins/publish/integrate_hero_version.py", line 223, in integrate_instance
  File "/cache/dev/OpenPype/openpype/client/server/operations.py", line 775, in update_entity
    project_name, entity_type, entity_id, update_data, self
  File "/cache/dev/OpenPype/openpype/client/server/operations.py", line 560, in __init__
    project_name, entity_id, update_data, self.con
  File "/cache/dev/OpenPype/openpype/client/server/conversion_utils.py", line 1172, in convert_update_hero_version_to_v4
    version = con.get_version_by_id(project_name, version_id)
  File "/cache/dev/OpenPype/openpype/vendor/python/common/ayon_api/server_api.py", line 3176, in get_version_by_id
    for version in versions:
  File "/cache/dev/OpenPype/openpype/vendor/python/common/ayon_api/server_api.py", line 3128, in get_versions
    for parsed_data in query.continuous_query(self):
  File "/cache/dev/OpenPype/openpype/vendor/python/common/ayon_api/graphql.py", line 370, in continuous_query
    response = con.query_graphql(query_str, variables)
  File "/cache/dev/OpenPype/openpype/vendor/python/common/ayon_api/server_api.py", line 1250, in query_graphql
    json=data
  File "/cache/dev/OpenPype/openpype/vendor/python/common/ayon_api/server_api.py", line 763, in _do_rest_request
    response = function(url, **kwargs)
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/cache/dev/OpenPype/.venv/lib/python3.9/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/autodesk/maya2022/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/autodesk/maya2022/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/autodesk/maya2022/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/autodesk/maya2022/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type object is not JSON serializable
```

I'm guessing that this is something connected to how OP db handles things vs. how Ayon likes things.

running the 'release/next-minor' branch

### Version

3.15.6-nightly.1

### What platform you are running OpenPype on?

Linux / Centos

### Steps To Reproduce:

1. Run ayon-backend docker, run Openpype with the release/next-minor branch. 
2. Launch maya. 
3. Publish a model.
4. publish again the same model (aiming for a v002 and a hero version pointing at v002). Hero integration fails.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-5880](https://app.clickup.com/t/861mruy19)]

**Comment by antirotor** [comment]
Just tested it in `3.17.5-nightly.1` and it works so it seems it was fixed.
