### ISSUE TITLE
Bug: Ayon Maya Review Creation - Profile key Error - 3.15.6-nightly.1 next-minor

### ISSUE THREAD

**Issue by Jeremyball** [ynput/OpenPype#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Doesn't create a Review subset

### Expected Behavior:

Create a review subset node

### Version

3.15.6-nightly.1

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

From Ayon menu in Maya

1. Create...
2. Select review
3. Create button
4. Error dialog

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Failed to create Subset: "reviewMain" Family: "review" in Asset: "chr"

Error: 'profiles'

Traceback (most recent call last):
  File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\tools\creator\window.py", line 431, in _on_create
    legacy_create(
  File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\pipeline\create\legacy_create.py", line 197, in legacy_create
    plugin = Creator(name, asset, options, data)
  File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\hosts\maya\plugins\create\create_review.py", line 44, in __init__
    preset = lib.get_capture_preset(
  File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\hosts\maya\api\lib.py", line 3931, in get_capture_preset
    if plugin_settings["profiles"]:
KeyError: 'profiles'
```

### Additional context:

release-next-minor
Maya 2023.2
Windows 11

[cuID:[OP-5887](https://app.clickup.com/t/861mt2d5a)]

**Comment by antirotor** [comment]
just tested in `3.17.5-nightly.2` and it seems it's working. Fixed by #4975
