### ISSUE TITLE
Bug: Repair action not working in Arnold Scene Source CBID Validator in Maya

### ISSUE THREAD

**Issue by moonyuet** [ynput/OpenPype#5095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

The repair function of Arnold Scene Source CBID Validator isn't working and errors out.

### Expected Behavior:

Repair action should run smoothly while making sure both content and proxy meshes are with the same CBID

### Version

3.15.10-nightly.1

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Launch Maya via Openpype
2. Create Arnold Scene Source Instance 
3. Run the publisher
4. Maker sure it triggers the Arnold Scene Source CBID validator
5. right click for repair function
6. It can't repair for you and pass the validation.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
# # ERROR - Traceback (most recent call last):
#   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\dependencies\pyblish\plugin.py", line 522, in __explicit_process
#     runner(*args)
#   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\pipeline\publish\publish_plugins.py", line 242, in process
#     plugin.repair(instance)
#   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\hosts\maya\plugins\publish\validate_arnold_scene_source_cbid.py", line 73, in repair
# TypeError: get_invalid_couples() takes 2 positional arguments but 3 were given
# Traceback (most recent call last):
#   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\dependencies\pyblish\plugin.py", line 522, in __explicit_process
#     runner(*args)
#   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\pipeline\publish\publish_plugins.py", line 242, in process
#     plugin.repair(instance)
#   File "<string>", line 73, in repair
TypeError: get_invalid_couples() takes 2 positional arguments but 3 were given
// Error: pyblish.plugin : Traceback (most recent call last):
//   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\dependencies\pyblish\plugin.py", line 522, in __explicit_process
//     runner(*args)
//   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\pipeline\publish\publish_plugins.py", line 242, in process
//     plugin.repair(instance)
//   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\hosts\maya\plugins\publish\validate_arnold_scene_source_cbid.py", line 73, in repair
// TypeError: get_invalid_couples() takes 2 positional arguments but 3 were given
// Traceback (most recent call last):
//   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\dependencies\pyblish\plugin.py", line 522, in __explicit_process
//     runner(*args)
//   File "D:\kayla\OpenPype\build\exe.win-amd64-3.9\openpype\pipeline\publish\publish_plugins.py", line 242, in process
//     plugin.repair(instance)
//   File "<string>", line 73, in repair
// TypeError: get_invalid_couples() takes 2 positional arguments but 3 were given
```
```


### Additional context:

_No response_


[cuID:[OP-6123](https://app.clickup.com/t/863gx8xqu)]

**Comment by moonyuet** [comment]
I create PR for this: https://github.com/ynput/OpenPype/pull/5096
