### ISSUE TITLE
Bug: missing time information on publishes from Tray Publisher

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#5136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Published instance no longer contain time data by default. This means that any family published with Simple Creators will miss it too, in effect breaking loading logic in loaders. For example:

Publishing `Plate` from Tray Publisher will publish stuff with missing frame range information on version. This version is then displayed incorrectly in the Loader and Clip Loader in Nuke will crash.

### Expected Behavior:

Tray Publisher - its collector - should add frame range information if it is publishing sequences. If files are list in representation, collect it using clique and set it. It is much more difficult to handle video files - in their case, it should either use something like ffprobe to get correct frame range (unreliable) or infer it from asset data (not precise enough).

### Version

3.15.9

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Open Tray Publisher
2. Select Project
3. Select your context
4. Select `Plate` as family
5. Drop some image sequence
6. Publish
7. Open Nuke
8. In Loader, you won't see any time information
9. `Load as Clip` will crash

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\tools\loader\widgets.py", line 1590, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\pipeline\load\utils.py", line 308, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\hosts\nuke\plugins\load\load_clip.py", line 125, in load
    first -= self.handle_start
TypeError: unsupported operand type(s) for -=: 'NoneType' and 'int'
```

**Comment by BigRoy** [comment]
There was this change a long time ago which is likely what removed it: https://github.com/ynput/OpenPype/pull/4383
However, I believe this PR https://github.com/ynput/OpenPype/pull/4891 should have re-added the missing data to what it was prior to #4383

**Comment by BigRoy** [comment]
It's good to note that the Nuke error mentioned above will STILL happen for standalone tray publishes if the Collect Asset Frame Data plug-in is disabled and the input for the publish is not a sequence but a video file.

So I'd actually recommend fixing the Nuke's `load_clip` logic too for the remainder cases.
