### ISSUE TITLE
Bug: Substance Painter - Publish Fails on "Collect Texture Set images"

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#5171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When trying to publish texture set via Publisher it fails on collecting Texture set images.

### Expected Behavior:

Publish should pass normally without errors.

### Version

3.15.11-nightly.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Open any asset workfile with painted asset
2. Publish Texture Set
3. Error probably occurs.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```
DEBUG: Exporting using preset: resource://starter_assets/PBR Metallic Roughness
INFO: Processing testMat/
INFO: Processing $mesh_$textureSet_BaseColor(_$colorSpace)(.$udim)
INFO: Looking for matching profile for: families: "texture" | hosts: "substancepainter" | tasks: "lookdev" | task_types: "Lookdev"
DEBUG: "texture" not found in "families": ['workfile']
DEBUG: "texture" not found in "families": ['render']
DEBUG: "texture" not found in "families": ['renderLayer', 'renderPass']
DEBUG: "texture" not found in "families": ['review', 'workfile']
DEBUG: "texture" not found in "families": ['render']
DEBUG: "texture" not found in "families": ['staticMesh']
DEBUG: "texture" not found in "families": ['skeletalMesh']
INFO: Profile selected: {'families': [], 'hosts': [], 'task_types': [], 'tasks': [], 'template': '{family}{variant}'}
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\substancepainter\plugins\publish\collect_textureset_images.py", line 43, in process
    self.create_image_instance(instance, template, outputs,
  File "D:\REPO\OpenPype\openpype\hosts\substancepainter\plugins\publish\collect_textureset_images.py", line 117, in create_image_instance
    image_instance.data.update(copy.deepcopy(instance.data))
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Program Files\Adobe\Adobe Substance 3D Painter\resources\pythonsdk\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'PySide2.QtWidgets.QMenu' object
```

_No response_

[cuID:[OP-6231](https://app.clickup.com/t/863h2ac9g)]

**Comment by BigRoy** [comment]
Thanks for the report.

I wonder what is adding a `QMenu` into the instance's data. I guess deepcopying becomes out of the question then.
