### ISSUE TITLE
Bug: Ftrack sync fails on new asset due to existing avalon/mongo id attributes

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#5236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Upon syncing ftrack to OpenPype an error is generated if two assets next to each other in the hierarchy (siblings) share the same Mongo/Avalon ID on Ftrack due to copying an asset or inheriting it from the parent on create. See **Steps to reproduce** for more information.

![image](https://github.com/ynput/OpenPype/assets/2439881/f66d3671-adfd-445f-bf13-5a1163e83140)

Error report:
```
Traceback (most recent call last):
  File "\openpype-v3.15.11-colorbleed.7\openpype\modules\ftrack\event_handlers_user\action_sync_to_avalon.py", line 80, in launch
    result = self.synchronization(event, project_name)
  File "\openpype-v3.15.11-colorbleed.7\openpype\modules\ftrack\event_handlers_user\action_sync_to_avalon.py", line 157, in synchronization
    self.entities_factory.synchronize()
  File "\openpype-v3.15.11-colorbleed.7\openpype\modules\ftrack\lib\avalon_sync.py", line 2023, in synchronize
    self.session.commit()
  File "C:\Program Files (x86)\OpenPype\3.15.11-colorbleed.1\dependencies\ftrack_api\session.py", line 1308, in commit
    result = self.call(batch)
  File "C:\Program Files (x86)\OpenPype\3.15.11-colorbleed.1\dependencies\ftrack_api\session.py", line 1687, in call
    raise ftrack_api.exception.ServerError(error_message)
ftrack_api.exception.ServerError: Server reported error: IntegrityError( "Duplicate entry '992288f-29b9-5e09-ac60-882211-prop_wallBar' for key 'context_parent_id_key'"))
```

I suspect we're running into this issue now more than before due to new producers in our studio who seem to be copy/pasting or creating assets in a different way than other producers have done so far.

### Expected Behavior:

Best case would be if duplicating and/or creating new assets on Ftrack wouldn't copy the Avalon/Mongo ID to begin with, but hey... it happens. So I'd say on sync, if there are clashes where a Mongo ID exists on two assets this is what should happen:

1. If one by same name already exists in the OpenPype database - the other not matching by name should get a new Avalon/Mongo ID assigned on Ftrack side.
2. If one by the ID already exists in he OpenPype database then I think the most sensible thing to do is to automatically regenerate the IDs on Ftrack side for the _newest created assets_ (`created_at` data) and keep the id on the oldest one.

I thought the first logic is was already in place but looking at what's occurring on our syncs that's not behaving as expected.

### Version

3.15.11

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

To reproduce:

_For sake of producing the reproducable, disable auto sync for a moment_

1. Create an asset underneath an existing asset that has publishes (this is important because assets seem to inherit the mongo id from its parent, even on duplicate it doesn't duplicate the id but takes it from its parent where you duplicated to)
2. Move the asset one folder up so it lives next to the other asset. You now have to different assets next to each other in hierarchy (siblings) that have the same avalon/mongo id.
    - An easier hack to reproduce the issue is by manually copy pasting the Mongo id from an existing asset to the new one.
3. Actions > OpenPype Admin > Sync to Avalon

I'm particularly mentioning clashing it with an existing asset that **has publishes** because that'll be what's holding the syncing from actually secretly "renaming" one of the entries in OpenPype database to avoid the ID clash and then change the ID of the other. At least, that's what helped me to reproduce it.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6320](https://app.clickup.com/t/861n0w2p7)]

**Comment by BigRoy** [comment]
Not sure if still relevant in `ayon-ftrack`. I'll close this because we've stopped using Ftrack on our side.
