### ISSUE TITLE
Bug: Kitsu entities collecting

### ISSUE THREAD

**Issue by aramadan0096** [ynput/OpenPype#5422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I have updated kitsu to version 0.17.14, I got this error while sycing to Kitsu using sync-service
openpype_console module kitsu sync-service -l me@domain.ext -p my_password

error:
`
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\kitsu_module.py", line 162, in sync_service
    start_listeners(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\utils\sync_service.py", line 639, in start_listeners
    listener = Listener(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\utils\sync_service.py", line 62, in __init__
    self.event_client = gazu.events.init()
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\gazu\events.py", line 44, in init
    event_client.connect(get_event_host(client), make_auth_header())
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\socketio\client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect

`
Then in NukeStudio 13.2.v2 when try to publish I get an error in collecting kitsu intities:

error:

`

Message: 
'DIT'
Line: 
36
Traceback: 
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\plugins\publish\collect_kitsu_entities.py", line 36, in process
KeyError: 'DIT'

`
![Screenshot 2023-08-07 225823](https://github.com/ynput/OpenPype/assets/57462754/f1fd03f0-f276-42e6-bc97-3f701559e331)

### Version

3.16.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

A new asset named "Conform" with a task "DIT"

![Screenshot 2023-08-07 230343](https://github.com/ynput/OpenPype/assets/57462754/9102ba1b-f23e-48b9-b6e9-bbc9903a5c4c)

Getting this error in publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
The entire error of syncing to Kitsu 
................................................................................................
>>> run disk mapping command ...
>>> Logging to server is turned ON
*** Cannot get OpenPype path from database.
>>> Finding latest version with [ 3.16.2 ]
  - booting version: 3.16.2
>>> Injecting OpenPype version to running environment  ...
>>> Validating version in frozen [ C:\Program Files (x86)\OpenPype\3.16.2 ]
--- version is valid
>>> loading environments ...
  - for Avalon ...
  - global OpenPype ...
  - for modules ...
*** OpenPype [ 3.16.2 ] ------------------------------------------------------------------------------------------------>>> Using OpenPype from [  C:\Program Files (x86)\OpenPype\3.16.2  ]
... OpenPype variant:      [  production  ]
... Running OpenPype from: [  C:\Program Files (x86)\OpenPype\3.16.2  ]
... Using mongodb:         [  192.168.1.2  ]
... Logging to MongoDB:    [  192.168.1.2  ]
...   - port:              [  <N/A>  ]
...   - database:          [  openpype  ]
...   - collection:        [  logs  ]
...   - user:              [  <N/A>  ]
>>> [  Synchronizing Movie106...  ]
>>> [  Refreshing token...  ]
!!! OpenPype crashed:
Traceback (most recent call last):
  File "start.py", line 1152, in boot
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\kitsu_module.py", line 162, in sync_service
    start_listeners(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\utils\sync_service.py", line 639, in start_listeners
    listener = Listener(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.2\openpype\modules\kitsu\utils\sync_service.py", line 62, in __init__
    self.event_client = gazu.events.init()
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\gazu\events.py", line 44, in init
    event_client.connect(get_event_host(client), make_auth_header())
  File "C:\Program Files (x86)\OpenPype\3.16.2\dependencies\socketio\client.py", line 347, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect



...............................................
```

**Comment by mustafa-zarkash** [comment]
> socketio.exceptions.ConnectionError: One or more namespaces failed to connect
I wonder why did it fail ? maybe they updated API ? I don't know

does this error happen when using lower versions of kitsu ?

**Comment by aramadan0096** [comment]
@mustafa-zarkash 
No I belive this is the first time a face this error

**Comment by aramadan0096** [comment]
When I downgraded to v0.15.11 I got this

```
>>> run disk mapping command ...
>>> Logging to server is turned ON
*** Cannot get OpenPype path from database.
>>> Finding latest version with [ 3.16.3 ]
  - booting version: 3.16.3
>>> Injecting OpenPype version to running environment  ...
>>> Validating version in frozen [ C:\Program Files (x86)\OpenPype\3.16.3 ]
--- version is valid
>>> loading environments ...
  - for Avalon ...
  - global OpenPype ...
  - for modules ...
*** OpenPype [ 3.16.3 ] ------------------------------------------------------------------------------------------------
>>> Using OpenPype from [  C:\Program Files (x86)\OpenPype\3.16.3  ]
... OpenPype variant:      [  production  ]
... Running OpenPype from: [  C:\Program Files (x86)\OpenPype\3.16.3  ]
... Using mongodb:         [  192.168.1.2  ]
... Logging to MongoDB:    [  192.168.1.2  ]
...   - port:              [  <N/A>  ]
...   - database:          [  openpype  ]
...   - collection:        [  logs  ]
...   - user:              [  <N/A>  ]
>>> [  Synchronizing Movie107...  ]
>>> [  Project created: Movie107  ]
*** WRN: >>> { DictImmutableKeysEntity }: [  project_settings/nuke/create/CreateWritePrerender Unknown keys in studio overrides: "reviewable", "defaults", "fpath_template", "knobs", "use_range_limit"  ]
*** WRN: >>> { DictImmutableKeysEntity }: [  project_settings/nuke/publish Unknown keys in studio overrides: "PreCollectNukeInstances"  ]
*** WRN: >>> { DictImmutableKeysEntity }: [  project_settings/nuke/create/CreateWritePrerender Unknown keys in studio overrides: "reviewable", "defaults", "fpath_template", "knobs", "use_range_limit"  ]
*** WRN: >>> { DictImmutableKeysEntity }: [  project_settings/nuke/publish Unknown keys in studio overrides: "PreCollectNukeInstances"  ]
>>> [  Refreshing token...  ]
The connection failed!
!!! OpenPype crashed:
Traceback (most recent call last):
  File "start.py", line 1152, in boot
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files (x86)\OpenPype\3.16.3\openpype\modules\kitsu\kitsu_module.py", line 162, in sync_service
    start_listeners(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.3\openpype\modules\kitsu\utils\sync_service.py", line 639, in start_listeners
    listener = Listener(login, password)
  File "C:\Program Files (x86)\OpenPype\3.16.3\openpype\modules\kitsu\utils\sync_service.py", line 62, in __init__
    self.event_client = gazu.events.init()
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\gazu\events.py", line 44, in init
    event_client.connect(get_event_host(client), make_auth_header())
  File "C:\Program Files (x86)\OpenPype\3.16.3\dependencies\socketio\client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Unexpected status code 400 in server response
```

**Comment by mustafa-zarkash** [comment]
> File "C:\Program Files (x86)\OpenPype\3.16.3\openpype\modules\kitsu\kitsu_module.py", line 162, in sync_service
    start_listeners(login, password)

I think I had your issue before this PR #4845 was merged. 
I really don't know why you are facing this issue however you can try this code inside openpype console. 

```python
import os 

# Credentials 
login = os.environ["KITSU_LOGIN"]
password = os.environ["KITSU_PWD"]

print(f"login: {login}\npassword: {password}\n")


# Sync All Projects
from openpype.modules.kitsu.utils.update_op_with_zou import sync_all_projects
sync_all_projects(login , password )
```

More about this snippet, [here](https://github.com/mustafa-zarkash/pipeline-technical-roadmap/blob/main/resources/code_snippets/openpype_kitsu_sync.py).

---
A little explanation: 

https://github.com/ynput/OpenPype/blob/328c3d9c7fa499ca39b1351b94f2d0ae0d261a69/openpype/modules/kitsu/kitsu_module.py#L159-L162

kitsu sync tool do two things 
1. `sync_all_projects`  (fetch all assets/shots from kitsu)
2. `start_listeners` (so that openpype can fetch new assets when they are created)

`start_listeners` fails but `sync_all_projects` seems to be working 
so, calling `sync_all_projects`  only may avoid facing your issue.

**Comment by aramadan0096** [comment]
@mustafa-zarkash Thanks it worked good for syncing, but I changed some settings to conform from a shot task insted of "conform asset" task.
I'll close the issue for now, Thanks again :)
