### ISSUE TITLE
Bug: Deadline publish job fail because of collect kitsu credentials

### ISSUE THREAD

**Issue by mustafa-zarkash** [ynput/OpenPype#5440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Openpype publish job fails to get `'KITSU_LOGIN'` and `'KITSU_LOGIN'`
```
2023-08-10 19:48:57:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2023-08-10 19:48:57:  0: STDOUT:   File "C:\Program Files (x86)\OpenPype\3.16.0\dependencies\pyblish\plugin.py", line 527, in __explicit_process
2023-08-10 19:48:57:  0: STDOUT:     runner(*args)
2023-08-10 19:48:57:  0: STDOUT:   File "C:\Users\Mustafa Taher\AppData\Local\pypeclub\openpype\3.16\openpype-v3.16.3-nightly.1\openpype\modules\kitsu\plugins\publish\collect_kitsu_credential.py", line 17, in process
2023-08-10 19:48:57:  0: STDOUT:   File "C:\Users\qam\.pyenv\pyenv-win\versions\3.9.7\lib\os.py", line 679, in __getitem__
2023-08-10 19:48:57:  0: STDOUT: KeyError: 'KITSU_LOGIN'
2023-08-10 19:48:57:  0: STDOUT: Traceback (most recent call last):
2023-08-10 19:48:57:  0: STDOUT:   File "C:\Program Files (x86)\OpenPype\3.16.0\dependencies\pyblish\plugin.py", line 527, in __explicit_process
2023-08-10 19:48:57:  0: STDOUT:     runner(*args)
2023-08-10 19:48:57:  0: STDOUT:   File "<string>", line 17, in process
2023-08-10 19:48:57:  0: STDOUT:   File "C:\Users\qam\.pyenv\pyenv-win\versions\3.9.7\lib\os.py", line 679, in __getitem__
2023-08-10 19:48:57:  0: STDOUT: KeyError: 'KITSU_LOGIN'
2023-08-10 19:48:57:  0: STDOUT: !!! ERR: 2023-08-10 19:48:57,122 >>> { CLI-publish }: [ Failed CollectKitsuSession: 'KITSU_LOGIN' -- ('C:\\Users\\Mustafa Taher\\AppData\\Local\\pypeclub\\openpype\\3.16\\openpype-v3.16.3-nightly.1\\openpype\\modules\\kitsu\\plugins\\publish\\collect_kitsu_credential.py', 679, '__getitem__', '') ] 
.
.
.
.
2023-08-10 16:16:38:  0: STDOUT: <class 'C:\Users\Mustafa Taher\AppData\Local\pypeclub\openpype\3.16\openpype-v3.16.3-nightly.1\openpype\modules\kitsu\plugins\publish\other_kitsu_log_out.py.KitsuLogOut'>
2023-08-10 16:16:38:  0: INFO: Process exit code: 1
2023-08-10 16:16:38:  0: Done executing plugin command of type 'Render Task'
```

### Expected Behavior:
Expected behavior that deadline job should be able to get `"KITSU_LOGIN"` and `"KITSU_PWD"` 
or simply we can submit them as `EnvironmentKeyValue` in job parameters like other env vars. 

### Version

3.16.3-nightly.5

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Get Kitsu installed (I have `0.16.12`)
2. Publish any job from deadline

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by mustafa-zarkash** [comment]
This problem no longer exists for some reason I don't know, Maybe there was something wrong with my OP's settings

**Comment by mustafa-zarkash** [comment]
> This problem no longer exists for some reason I don't know

Yeah, because I accidentally turned off kitsu module 🤦‍♂️
![image](https://github.com/ynput/OpenPype/assets/20871534/b83bab4c-1826-438e-9b1d-995e56ef9863)
