### ISSUE TITLE
Bug: Unable to publish USD cache in houdini

### ISSUE THREAD

**Issue by krishna8008** [ynput/OpenPype#5504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Getting an error when publishing in USD,
![image](https://github.com/ynput/OpenPype/assets/61413765/f872b37a-b6d9-4930-b9cf-fbdc2b1dcfa6)

### Expected Behavior:

Publish should be complete without any errors

### Version

3.16.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. publish any geometry with LOPS USD in houdini

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
INFO: Writing USD 'usdCar_mesh_fx.usd' to 'J:/littleblackstar/APE_Media_content/Story/Story_sh001/work/FX/pyblish'
Traceback (most recent call last):
  File "C:\Users\Adeshbhor\AppData\Local\pypeclub\openpype\3.16\openpype-v3.16.4\openpype\hosts\houdini\api\lib.py", line 279, in render_rop
    output_progress=verbose)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.7libs\houpythonportion\ui.py", line 1119, in decorator
    return func(*args, **kwargs)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.569/houdini/python3.7libs\hou.py", line 74216, in render
    return _hou.RopNode_render(self, *args, **kwargs)
hou.OperationFailed: The attempted operation failed.
Error:       Layer saved to a location generated from a node path: J:/littleblackstar/APE_Media_content/Story/Story_sh001/work/FX/pyblish/obj/growth_cars_TEST/Car_mesh_fx.usd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\3.16.0\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\Adeshbhor\AppData\Local\pypeclub\openpype\3.16\openpype-v3.16.4\openpype\hosts\houdini\plugins\publish\extract_usd.py", line 31, in process
    render_rop(ropnode)
  File "C:\Users\Adeshbhor\AppData\Local\pypeclub\openpype\3.16\openpype-v3.16.4\openpype\hosts\houdini\api\lib.py", line 286, in render_rop
    raise RuntimeError("Render failed: {0}".format(exc))
RuntimeError: Render failed: The attempted operation failed.
Error:       Layer saved to a location generated from a node path: J:/littleblackstar/APE_Media_content/Story/Story_sh001/work/FX/pyblish/obj/growth_cars_TEST/Car_mesh_fx.usd
```

**Comment by BigRoy** [comment]
If I recall correctly, I think you'll need to set up your USD network in such a way that it doesn't generate extra separate layers within the single publish for a specific node tree. You can reference separate USD layers, etc. but the single publish itself was never built in such a way to generate relative USD files within the one publish. I think it was "layer break" or something that enforced to do that or a toggle on SOP imports to flatten into the current USD tree (because otherwise the SOP import would be its own USD layered in in the export.)

**Comment by krishna8008** [comment]
Understood!
This solved my issue:
![image](https://github.com/ynput/OpenPype/assets/61413765/bb6633d9-2161-41e1-8cd2-37a6d1563a47)


Its not a OP bug, Thanks @BigRoy
