### ISSUE TITLE
Bug: Nuke ExtractReviewDataMov fails if more than one output profile

### ISSUE THREAD

**Issue by jrsndl** [ynput/OpenPype#5506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Using more than one ExtractReviewDataMov output definitions, publish fails on integrating the asset. Each output definition creates a thumbnail, but only one thumbnail can be published. Publish stops 'cause it doesn't allow to overwrite files already in the queue.

### Expected Behavior:

Ideally, there should be a settings for output profile that should be used for Thumbnail.
Or maybe just allowing FileTransaction  allow_queue_replacements=True would be OK fof integrating Thumbnails?

### Version

3.16.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Set project_settings/nuke/publish/ExtractReviewDataMov to have two output profiles
2. Publish the Nuke render
![image](https://github.com/ynput/OpenPype/assets/45896205/b2ea4d2d-a1b3-47d2-bd85-bc1bfaddddd4)
![image](https://github.com/ynput/OpenPype/assets/45896205/7a9a043f-a19d-4d7c-893e-5372eef93216)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
DEBUG: Establishing staging directory @ \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\work\comp\renders\nuke\renderCompMain
DEBUG: Looking for matching profile for: hosts: "nuke" | families: "render" | task_names: "comp" | task_types: "Compositing"
DEBUG: "nuke" not found in "hosts": ['standalonepublisher']
DEBUG: "nuke" not found in "hosts": ['maya']
DEBUG: "nuke" not found in "hosts": ['traypublisher']
DEBUG: Profile selected: {'families': ['review', 'render', 'prerender'], 'hosts': [], 'task_types': [], 'task_names': [], 'template_name': 'render'}
DEBUG: Subset: renderCompMain
INFO: Subset 'renderCompMain' not found, creating ...
DEBUG: Prepared subset: renderCompMain
DEBUG: Source: {root[work]}/T029_OP3_16_3_tst/shots/sq01test02/sq01tst02_sh060/work/comp/sq01tst02_sh060_comp_v000.nk
DEBUG: Creating new version ...
DEBUG: Prepared version: v000
DEBUG: Anatomy template name: render
DEBUG: Template filled: //dazzle.local/shares/pype_dev/projects/T029_OP3_16_3_tst/shots/sq01test02/sq01tst02_sh060/publish/render/renderCompMain/v000//sq01tst02_sh060_renderCompMain_v000.1000.exr
DEBUG: Anatomy template name: render
DEBUG: Anatomy template name: render
Traceback (most recent call last):
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\plugins\publish\integrate.py", line 181, in process
    self.register(instance, file_transactions, filtered_repres)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\plugins\publish\integrate.py", line 281, in register
    file_transactions.add(src, dst)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\lib\file_transaction.py", line 98, in add
    raise DuplicateDestinationError(
openpype.lib.file_transaction.DuplicateDestinationError: Transfer to destination is already in queue: \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\work\comp\renders\nuke\renderCompMain\renderCompMain_baking.jpg -> \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\publish\render\renderCompMain\v000\_thumb\sq01tst02_sh060_renderCompMain_v000_thumb.jpg. It's not allowed to be replaced by a new transfer from \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\work\comp\renders\nuke\renderCompMain\renderCompMain_LOGhd.jpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\plugins\publish\integrate.py", line 186, in process
    six.reraise(KnownPublishError,
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\.venv\lib\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\plugins\publish\integrate.py", line 181, in process
    self.register(instance, file_transactions, filtered_repres)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\plugins\publish\integrate.py", line 281, in register
    file_transactions.add(src, dst)
  File "\\dazzle.local\shares\pype_dev\_code\OP3\3.16.5-nightly.1\openpype\lib\file_transaction.py", line 98, in add
    raise DuplicateDestinationError(
openpype.pipeline.publish.publish_plugins.KnownPublishError: Transfer to destination is already in queue: \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\work\comp\renders\nuke\renderCompMain\renderCompMain_baking.jpg -> \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\publish\render\renderCompMain\v000\_thumb\sq01tst02_sh060_renderCompMain_v000_thumb.jpg. It's not allowed to be replaced by a new transfer from \\dazzle.local\shares\pype_dev\projects\T029_OP3_16_3_tst\shots\sq01test02\sq01tst02_sh060\work\comp\renders\nuke\renderCompMain\renderCompMain_LOGhd.jpg
```

**Comment by jrsndl** [comment]
As a quick (bad) fix, allowing file transactions to overwrite the queue allows publish to continue:
https://github.com/ynput/OpenPype/blob/67abbaad3c2bdbbf561bc7d30d6ac1adc5b21ed8/openpype/plugins/publish/integrate.py#L179C70-L179C75

**Comment by jrsndl** [comment]
Interestingly, when adding profile to Override Integrate Thumbnail Representation
(project_settings/global/publish/PreIntegrateThumbnails),
Integrate doesn't fail on double Thumbnail. I would take it as a solution for now...
![image](https://github.com/ynput/OpenPype/assets/45896205/71230d7b-0259-4d9b-b2c8-f46ea84d3ad4)

**Comment by jakubjezek001** [comment]
Confirming the issue is happening also in Ayon and OpenPype at version `3.17.2-nightly-1`
