### ISSUE TITLE
Enhancement: Maya Xgen Interactive support in OP (missing feature)

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#5778]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently there is no support for ```Xgen Interactive``` grooming in OP.

When trying to ```Publish``` via ```XgenMain``` fails on collecting phase with following errors:

```
DEBUG: Collected inputs: []
DEBUG: publishDir: "D:\Projects\Libor_Tests\assets\characters\rayman\publish\xgen\xgenMain\v010"
DEBUG: resourcesDir: "D:\Projects\Libor_Tests\assets\characters\rayman\publish\xgen\xgenMain\v010\resources"
DEBUG: Not adding custom staging dir for instance with 'xgen'
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\collect_xgen.py", line 44, in process
    "xgDataPath", data["xgmPalette"].replace("|", "")
KeyError: 'xgmPalette'
```

### How would you imagine the implementation of the feature?

Support Xgen Interactive type in OP. Using existing ```Xgen``` family/Instance or by dedicating new Instance type as
```Xgen Interactive``` when used for grooming.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by tokejepsen** [comment]
Can you convert interactive to standard xgen?

**Comment by LiborBatek** [comment]
> Can you convert interactive to standard xgen?

According to Adesk docs this conversion not being possible. Only when going from Guides/Descriptions > Interactive Groom
