### ISSUE TITLE
Maya: Switching Rigs between legacy published rigs and current

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#5788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

PR #5310 added prefixes to objectSets to avoid issues with multiple rig variants in the same scene and set naming. It broke asset switching unfortunately.

**rigMain_v001** is a *legacy rig* - it has `control_SET` and `out_SET`
**rigMain_v002** is *current-style* rig - it has `rigMain_control_SET` and `rigMain_out_SET`

if you have **v001** loaded in the scene and you are switching to **v002**, maya will create `[placeholder]` sets and mess up the hierarchy, subsequently breaking publishing because the *Validate Content Rig* will correctly fails.

This will happen also the other way around, switching from **v002** to **v001**.

### Expected Behavior:

Switching rigs should work as expected even with backwards compatible manner.

### Version

3.17.3-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Switch between old-style and new-style published Maya rigs.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
We have a fix for this implemented actually - not entirely sure where I have that code. It's in our `colorbleed` branch at least.

**Comment by LiborBatek** [comment]
@BigRoy  here is the error msg during Validation:
```
// Error: pyblish.plugin : Traceback (most recent call last):
//   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_animation_content.py", line 51, in process
//     invalid = self.get_invalid(instance)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_animation_content.py", line 29, in get_invalid
//     assert out_set, ("Instance '%s' has no objectSet named: `OUT_set`. "
// AssertionError: Instance 'animation_rayman_rigMain_01_' has no objectSet named: `OUT_set`. If this instance is an unloaded reference, please deactivate by toggling the 'Active' attribute
// Traceback (most recent call last):
//   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_animation_content.py", line 51, in process
//     invalid = self.get_invalid(instance)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_animation_content.py", line 29, in get_invalid
//     assert out_set, ("Instance '%s' has no objectSet named: `OUT_set`. "
// AssertionError: Instance 'animation_rayman_rigMain_01_' has no objectSet named: `OUT_set`. If this instance is an unloaded reference, please deactivate by toggling the 'Active' attribute
```
I have also recorded the full process

https://github.com/ynput/OpenPype/assets/112623825/d4196697-4de9-4b67-b4e7-26015c6b412f

**Comment by BigRoy** [comment]
Thanks - I believe I added a repair action for this case! :)

It's in [here](https://github.com/BigRoy/OpenPype/blob/colorbleed/openpype/hosts/maya/plugins/publish/validate_animation_content.py)

So it will still invalidate - but repair will clean up the placeholder list entries in the outliner and swap them around for the correct new sets 👍
