### ISSUE TITLE
BUg: Empty Deadline pools validation issue

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#5806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When render instance is created in 3dsmax and primary/secondary pools are empty, following error will happen in validation phase:

![image](https://github.com/ynput/OpenPype/assets/33513211/618fd5a0-37ad-4a70-bf4c-1bc9ed4dea91)

Note that in this case, no pools are defined in Deadline.

Related #3057

### Expected Behavior:

Empty pools should be supported. Submission with empty pools set should still work.

### Version

3.17.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Don't fill any pool names in Render creator (in my case it was in 3dsmax)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\ayon-desktop\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\ayon-desktop\openpype\modules\deadline\plugins\publish\validate_deadline_pools.py", line 57, in process
    raise PublishXmlValidationError(
openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Primary pool 'none' not available on Deadline
Secondary pool 'none' not available on Deadline
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\ayon-desktop\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\ayon-desktop\openpype\modules\deadline\plugins\publish\validate_deadline_pools.py", line 57, in process
    raise PublishXmlValidationError(
openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Primary pool 'none' not available on Deadline
Secondary pool 'none' not available on Deadline
```

### Additional context:

I suspect there is some conversion to Deadline string `none` somewhere.

**Comment by Sponge96** [comment]
I don't believe the problem originates from the presence of 'none' values in this instance.

 https://github.com/ynput/OpenPype/blob/b382b7c77609be4b78fbd00e0758a1e3218224b8/openpype/modules/deadline/deadline_module.py#L72-L74
The warning you received indicates that the request to Deadline failed, leading to an empty list being returned.

This poses a problem in validation, as it compares against the empty list at this location (pools): https://github.com/ynput/OpenPype/blob/b382b7c77609be4b78fbd00e0758a1e3218224b8/openpype/modules/deadline/plugins/publish/validate_deadline_pools.py#L44-L45

causing:
https://github.com/ynput/OpenPype/blob/b382b7c77609be4b78fbd00e0758a1e3218224b8/openpype/modules/deadline/plugins/publish/validate_deadline_pools.py#L51-L61

I suggest considering raising an actual error if the pools request fails, as it could indicate a broader problem with the Deadline. Alternatively (although not my preferred solution), it could submit if 'none' is encountered, regardless of whether pools are set to [] (indicating the request to Deadline failed).

Note: In my testing, Deadline returns 'none' inside the list of pools if response.ok by default, and 3dsmax render publish works as intended if Primary/Secondary pools are set to nothing.
